### ISSUE TITLE
Error while running on Ubuntu machine

### ISSUE THREAD

**Issue by jitu9954** [as19git67/simnuki#1]
I am trying to rub the simulator on Ubuntu machine but getting below error...any suggestions?

$ sudo npm install
|

> sodium@1.1.15 preinstall /home/alsm_user/Downloads/simnuki-master/node_modules/sodium
> node install.js --preinstall

Static libsodium was not found at /home/alsm_user/Downloads/simnuki-master/node_modules/sodium/deps/build/lib/libsodium so compiling libsodium from source.
autoconf is required, but wasn't found on this system
Makefile:61: recipe for target 'libsodium' failed
make: **\* [libsodium] Error 1
/home/alsm_user/Downloads/simnuki-master/node_modules/sodium/install.js:279
            throw new Error(cmdLine + ' exited with code ' + code);
            ^

Error: make libsodium exited with code 2
    at ChildProcess.<anonymous> (/home/alsm_user/Downloads/simnuki-master/node_modules/sodium/install.js:279:19)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! sodium@1.1.15 preinstall: `node install.js --preinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sodium@1.1.15 preinstall script 'node install.js --preinstall'.
npm ERR! This is most likely a problem with the sodium package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js --preinstall
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sodium
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls sodium
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/alsm_user/Downloads/simnuki-master/npm-debug.log

**Comment by ptthisdan** [comment]
sudo apt-get install autotools-dev autoconf
npm install sodium
